pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven build and SonarQube analysis') {
            agent {
                docker {
                    image 'maven:3.9-eclipse-temurin-21'
                    args '--network devops -v $HOME/.m2:/root/.m2'
                    reuseNode true
                }
            }

            steps {
                dir('biblio-back') {
                    withSonarQubeEnv('sonar') {
                        sh "mvn clean verify sonar:sonar -Dspring.datasource.url='jdbc:mysql://app-mysql:3306/projet_biblio?createDatabaseIfNotExist=true' -Dspring.datasource.username=root -Dspring.datasource.password=root -Dsonar.projectKey=biblio-back -Dsonar.projectName='biblio-back' -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml"
                    }
                }
            }
        }

        stage('SonarQube Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker build') {
            steps {
                sh 'docker build -t biblioback -f biblio-back/Dockerfile .'
            }
        }
    }
}
