# Le nom du compose, optionel
name: biblio-compose

# Décrire tous les services, volumes, network, etc. nécessaire au bon fonctionnement

# Descrription des différents containers
services:
  # Description du container "PostgreSQL"
  mysql:
    image: mysql:8.0.45
    container_name: app-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      # Pour initialiser la base
      - ./biblio-back/demo-init.sql:/docker-entrypoint-initdb.d/init.sql

      # Pour persister les données après suppression / mise à jour du container
      - mysql_data:/var/lib/mysql

    networks:
      - devops

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    image: biblioback
    container_name: biblio-back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projet_biblio?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    networks:
      - devops

    ports:
      - 8080:8080

    depends_on:
      mysql:
        condition: service_healthy

  web:
    image: biblioAngular
    container_name: angular
    ports:
      - 4201:4201
    networks:
      - devops
    depends_on:
      - java

networks:
  devops:
    name: devops

volumes:
  mysql_data:
    name: demo-mysql-data
