pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('NPM install, build and SonarQube analysis') {
            agent {
                docker {
                    image 'node:22'
                    args '--network devops -v $HOME/.npm:/root/.npm'
                    reuseNode true
                }
            }

            steps {
                dir('biblio-angular') {
                    withSonarQubeEnv('sonar') {
                        sh '''
                            npm install
                            npm run build
                            npx sonar-scanner
                        '''
                    }
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('biblio-angular') {
                    sh 'docker build -t ajc/biblio-front .'
                }
            }
        }
    }
}
