pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('NPM install and build') {
            agent {
                docker {
                    image 'node:22'
                    args '--network devops -v $HOME/.npm:/root/.npm'
                    reuseNode true
                }
            }

            steps {
                dir('biblio-angular') {
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }

        stage('Sonar analysis') {
            agent {
                docker {
                    image 'node:22'
                    args '--network devops -v $HOME/.npm:/root/.npm'
                    reuseNode true
                }
            }

            steps {
                dir('biblio-angular') {
                    withSonarQubeEnv('sonar') {
                        sh './node_modules/.bin/sonar-scanner -Dsonar.projectKey=biblio-angular'
                    }
                }
            }
        }

        stage('SonarQube Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker build') {
            steps {
                sh 'docker build -t ajc/biblio-front -f biblio-angular/Dockerfile .'
            }
        }
    }
}
