pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('NPM install, build and SonarQube analysis') {
            agent {
                docker {
                    image 'node:22'
                    args '--network devops -v $HOME/.npm:/root/.npm'
                    reuseNode true
                }
            }

            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                        npm install
                        npm run build
                        npx sonar-scanner
                    '''
                }
            }
        }

        stage('SonarQube Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker build') {
            steps {
                sh 'docker build -t ajc/biblio-front .'
            }
        }
    }
}
